# Generated by Django 4.1.5 on 2023-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='additional_info',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
