# Generated by Django 4.1.5 on 2023-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0002_alter_address_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
