# Generated by Django 4.1.5 on 2023-01-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autographs', '0003_alter_letter_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='additional_info',
            field=models.CharField(max_length=256, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=128, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='autographs.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=128, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=128, verbose_name='Zip-code'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autographs.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='is_responded',
            field=models.BooleanField(default=False, verbose_name='Is responded'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Response date'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='send_date',
            field=models.DateField(verbose_name='Send date'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='autographs.person', verbose_name='To whom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last name'),
        ),
    ]
